import React, { useState, useMemo, useRef } from "react";

const C = 3e8;
const GROUND_T = 0.035;
const TRACE_T = 0.01;

const DEFAULTS = {
  subL: 50, subW: 30, subH: 0.5, epsR: 3.66, tanD: 0.0037,
  orOuter: 12.5, orInner: 10, irOuter: 6, irInner: 2,
  ctrX: -2, feedW: 2, connW: 2, targetF: 2.45,
};

const PRESETS = {
  "Rogers RO4350B": { epsR: 3.66, tanD: 0.0037 },
  "FR-4": { epsR: 4.4, tanD: 0.02 },
  "Rogers RT/duroid 5880": { epsR: 2.2, tanD: 0.0009 },
  "Rogers RO3003": { epsR: 3.0, tanD: 0.001 },
};

function ringPath(cx, cy, rOut, rIn) {
  return [
    `M ${cx + rOut} ${cy}`,
    `A ${rOut} ${rOut} 0 1 1 ${cx - rOut} ${cy}`,
    `A ${rOut} ${rOut} 0 1 1 ${cx + rOut} ${cy} Z`,
    `M ${cx + rIn} ${cy}`,
    `A ${rIn} ${rIn} 0 1 0 ${cx - rIn} ${cy}`,
    `A ${rIn} ${rIn} 0 1 0 ${cx + rIn} ${cy} Z`,
  ].join(" ");
}

function epsEff(er, w, h) {
  const r = w / h;
  if (r >= 1) return (er + 1) / 2 + ((er - 1) / 2) / Math.sqrt(1 + 12 * h / w);
  return (er + 1) / 2 + ((er - 1) / 2) * (1 / Math.sqrt(1 + 12 * h / w) + 0.04 * (1 - w / h) ** 2);
}

function feedZ0(er, w, h) {
  const ee = epsEff(er, w, h);
  const r = w / h;
  if (r <= 1) return (60 / Math.sqrt(ee)) * Math.log(8 * h / w + w / (4 * h));
  return (120 * Math.PI) / (Math.sqrt(ee) * (r + 1.393 + 0.667 * Math.log(r + 1.444)));
}

function Slider({ label, value, min, max, step, unit, onChange }) {
  const decimals = step < 0.01 ? 4 : step < 0.1 ? 2 : step < 1 ? 1 : 0;
  return (
    <div className="flex items-center gap-2 mb-1.5">
      <span className="text-xs text-slate-400 w-20 shrink-0 select-none">{label}</span>
      <input type="range" min={min} max={max} step={step} value={value}
        onChange={e => onChange(parseFloat(e.target.value))}
        style={{ flex: 1, accentColor: "#22d3ee", height: 4 }} />
      <span className="text-xs text-slate-200 w-20 text-right shrink-0"
        style={{ fontFamily: "monospace" }}>{value.toFixed(decimals)} {unit}</span>
    </div>
  );
}

function Section({ title, children }) {
  return (
    <div className="mb-3">
      <div className="text-xs font-semibold text-cyan-400 uppercase tracking-wider mb-1.5 select-none">{title}</div>
      {children}
    </div>
  );
}

function MetricCard({ label, value, unit, warn }) {
  return (
    <div className="p-2 rounded" style={{ background: warn ? "#7f1d1d33" : "#1e293b", border: `1px solid ${warn ? "#dc2626" : "#334155"}` }}>
      <div className="text-xs text-slate-400 select-none">{label}</div>
      <div className="text-lg font-semibold" style={{ fontFamily: "monospace", color: warn ? "#fca5a5" : "#e2e8f0" }}>
        {value} <span className="text-xs text-slate-400 font-normal">{unit}</span>
      </div>
    </div>
  );
}

export default function AntennaDesigner() {
  const [p, setP] = useState(DEFAULTS);
  const [tab, setTab] = useState("design");
  const [aiQuery, setAiQuery] = useState("");
  const [aiResp, setAiResp] = useState("");
  const [aiLoading, setAiLoading] = useState(false);
  const codeRef = useRef(null);

  const set = (k, v) => setP(prev => ({ ...prev, [k]: v }));

  const calc = useMemo(() => {
    const rw = p.orOuter - p.orInner;
    const ee = epsEff(p.epsR, rw > 0 ? rw : 0.1, p.subH);
    const meanR = (p.orOuter + p.orInner) / 2 * 1e-3;
    const fRes = meanR > 0 ? C / (2 * Math.PI * meanR * Math.sqrt(ee)) / 1e9 : 0;
    const z0 = feedZ0(p.epsR, p.feedW, p.subH);
    const lam0 = fRes > 0 ? C / (fRes * 1e9) * 1e3 : 0;
    const lamG = fRes > 0 ? lam0 / Math.sqrt(ee) : 0;
    const delta = fRes - p.targetF;
    const hLam = fRes > 0 ? p.subH / lam0 : 0;
    return { fRes, z0, lam0, lamG, delta, ee, hLam, rw };
  }, [p]);

  const warnings = useMemo(() => {
    const w = [];
    if (p.orInner >= p.orOuter) w.push("Outer ring: inner ≥ outer radius");
    if (p.irInner >= p.irOuter) w.push("Inner ring: inner ≥ outer radius");
    if (p.irOuter >= p.orInner) w.push("Inner ring overlaps outer ring");
    if (p.ctrX + p.orOuter > p.subL / 2) w.push("Ring extends past substrate (right)");
    if (p.ctrX - p.orOuter < -p.subL / 2) w.push("Ring extends past substrate (left)");
    if (p.orOuter > p.subW / 2) w.push("Ring extends past substrate (top/bottom)");
    return w;
  }, [p]);

  // Geometry helpers
  const feedStartX = p.ctrX + p.orOuter - calc.rw * 0.2;
  const feedEndX = p.subL / 2;
  const connX1 = p.ctrX - p.irOuter + 1;
  const connX2 = p.ctrX - p.orInner - 1;

  // VBA code generation
  const vba = useMemo(() => {
    const sL2 = p.subL / 2, sW2 = p.subW / 2;
    const fY = p.feedW / 2, cY = p.connW / 2;
    const p2z = -(p.subH + GROUND_T);
    return `Option Explicit
Sub Main()
' ============================================================
'  Concentric Ring Antenna – auto-generated by Antenna Designer
'  Target: ${p.targetF} GHz | Substrate: ${p.subL}x${p.subW}x${p.subH} mm
'  Estimated f_res: ${calc.fRes.toFixed(3)} GHz
' ============================================================

On Error Resume Next
Port.Delete "1"
Monitor.Delete "farfield (f=${p.targetF})"
Monitor.Delete "e-field (f=${p.targetF})"
Component.Delete "component1"
Material.Delete "Copper (annealed)"
Material.Delete "Substrate Material"
On Error GoTo 0

' ---- Materials ----
With Material
  .Reset
  .Name "Copper (annealed)"
  .FrqType "all"
  .Type "Lossy metal"
  .SetMaterialUnit "GHz","mm"
  .Mu "1.0"
  .Kappa "5.8e+007"
  .Rho "8930.0"
  .Colour "1","1","0"
  .Create
End With

With Material
  .Reset
  .Name "Substrate Material"
  .FrqType "all"
  .Type "Normal"
  .SetMaterialUnit "GHz","mm"
  .Epsilon "${p.epsR}"
  .Mu "1.0"
  .Kappa "0.0"
  .TanD "${p.tanD}"
  .TanDFreq "10.0"
  .TanDGiven "True"
  .TanDModel "ConstTanD"
  .Colour "0.94","0.82","0.76"
  .Create
End With

' ---- Substrate & Ground ----
Component.New "component1"

With Brick
  .Reset
  .Name "Substrate"
  .Component "component1"
  .Material "Substrate Material"
  .Xrange "${-sL2}","${sL2}"
  .Yrange "${-sW2}","${sW2}"
  .Zrange "0","${p.subH}"
  .Create
End With

With Brick
  .Reset
  .Name "Ground"
  .Component "component1"
  .Material "Copper (annealed)"
  .Xrange "${-sL2}","${sL2}"
  .Yrange "${-sW2}","${sW2}"
  .Zrange "${-GROUND_T}","0"
  .Create
End With

' ---- Align WCS to top face ----
Pick.PickFaceFromId "component1:Substrate", "1"
WCS.AlignWCSWithSelected "Face"
WCS.ActivateWCS "local"

' ---- Feed Strip ----
With Brick
  .Reset
  .Name "Feed"
  .Component "component1"
  .Material "Copper (annealed)"
  .Xrange "${feedStartX.toFixed(2)}","${feedEndX}"
  .Yrange "${(-fY).toFixed(2)}","${fY.toFixed(2)}"
  .Zrange "0","${TRACE_T}"
  .Create
End With

' ---- Outer Ring ----
With Cylinder
  .Reset
  .Name "Outer Ring"
  .Component "component1"
  .Material "Copper (annealed)"
  .OuterRadius "${p.orOuter}"
  .InnerRadius "${p.orInner}"
  .Axis "z"
  .Zrange "0","${TRACE_T}"
  .Xcenter "${p.ctrX}"
  .Ycenter "0"
  .Segments "0"
  .Create
End With

' ---- Inner Ring ----
With Cylinder
  .Reset
  .Name "Inner Ring"
  .Component "component1"
  .Material "Copper (annealed)"
  .OuterRadius "${p.irOuter}"
  .InnerRadius "${p.irInner}"
  .Axis "z"
  .Zrange "0","${TRACE_T}"
  .Xcenter "${p.ctrX}"
  .Ycenter "0"
  .Segments "0"
  .Create
End With

' ---- Connector Bridge (inner to outer ring) ----
With Brick
  .Reset
  .Name "Inner Outer Connect"
  .Component "component1"
  .Material "Copper (annealed)"
  .Xrange "${connX1.toFixed(2)}","${connX2.toFixed(2)}"
  .Yrange "${(-cY).toFixed(2)}","${cY.toFixed(2)}"
  .Zrange "0","${TRACE_T}"
  .Create
End With

' ---- Boolean union ----
Solid.Add "component1:Feed", "component1:Inner Outer Connect"
Solid.Add "component1:Inner Ring", "component1:Outer Ring"
Solid.Add "component1:Feed", "component1:Inner Ring"

' ---- Frequency & Monitors ----
Solver.FrequencyRange "1","4"

With Monitor
  .Reset
  .Name "farfield (f=${p.targetF})"
  .Domain "Frequency"
  .FieldType "Farfield"
  .MonitorValue "${p.targetF}"
  .ExportFarfieldSource "False"
  .Create
End With

With Monitor
  .Reset
  .Name "e-field (f=${p.targetF})"
  .Dimension "Volume"
  .Domain "Frequency"
  .FieldType "Efield"
  .MonitorValue "${p.targetF}"
  .Create
End With

' ---- Discrete Face Port ----
' NOTE: Edge IDs (below) correspond to the default geometry.
'       If you change ring radii significantly, you may need to
'       re-pick edges manually in CST or update the IDs.
Pick.PickEdgeFromId "component1:Feed", "21", "17"
Pick.PickEdgeFromId "component1:Ground", "5", "5"

With DiscreteFacePort
  .Reset
  .PortNumber "1"
  .Type "SParameter"
  .Impedance "50.0"
  .VoltageAmplitude "1.0"
  .CurrentAmplitude "1.0"
  .Monitor "True"
  .CenterEdge "True"
  .SetP1 "True", "${sL2}", "0", "${TRACE_T}"
  .SetP2 "True", "${sL2}", "0", "${p2z.toFixed(3)}"
  .LocalCoordinates "True"
  .InvertDirection "False"
  .UseProjection "False"
  .ReverseProjection "False"
  .FaceType "Linear"
  .Create
End With

' ---- Mesh ----
With MeshSettings
  .SetMeshType "Hex"
  .Set "StepsPerWaveNear", "10"
  .Set "StepsPerWaveFar", "10"
  .Set "StepsPerBoxNear", "10"
End With

' ---- Time-domain solver ----
ChangeSolverType "HF Time Domain"
Mesh.SetCreator "High Frequency"

With Solver
  .Method "Hexahedral"
  .CalculationType "TD-S"
  .StimulationPort "All"
  .StimulationMode "All"
  .SteadyStateLimit "-40"
  .MeshAdaption "False"
  .AutoNormImpedance "True"
  .NormingImpedance "50"
End With

WCS.ActivateWCS "global"
End Sub`;
  }, [p, calc, feedStartX, feedEndX, connX1, connX2]);

  // AI advisor
  const askAI = async (q) => {
    const query = q || aiQuery;
    if (!query.trim()) return;
    setAiLoading(true);
    setAiResp("");
    try {
      const sysPrompt = `You are an expert RF and antenna engineer advising a university student. They are designing a concentric double-ring microstrip antenna for WiFi at ${p.targetF} GHz.

Current parameters:
- Substrate: ${p.subL}×${p.subW}×${p.subH} mm, εr=${p.epsR}, tanδ=${p.tanD}
- Outer ring: outer R=${p.orOuter}mm, inner R=${p.orInner}mm (width=${calc.rw.toFixed(1)}mm)
- Inner ring: outer R=${p.irOuter}mm, inner R=${p.irInner}mm
- Ring center offset: X=${p.ctrX}mm
- Feed width: ${p.feedW}mm, connector bridge width: ${p.connW}mm

Analytical estimates:
- Resonant frequency ≈ ${calc.fRes.toFixed(3)} GHz (target: ${p.targetF} GHz, error: ${(calc.delta * 1000).toFixed(0)} MHz)
- Feed impedance ≈ ${calc.z0.toFixed(1)} Ω
- εeff ≈ ${calc.ee.toFixed(3)}
- Guided wavelength ≈ ${calc.lamG.toFixed(1)} mm

Give specific, actionable advice with exact numerical suggestions. Keep response under 250 words. Use plain text, no markdown headers or bullets. Reference specific parameters by name.`;

      const resp = await fetch("https://api.anthropic.com/v1/messages", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          model: "claude-sonnet-4-6",
          max_tokens: 1000,
          system: sysPrompt,
          messages: [{ role: "user", content: query }],
        }),
      });
      const data = await resp.json();
      const text = data.content?.map(b => b.text || "").join("\n") || "No response received.";
      setAiResp(text);
    } catch (err) {
      setAiResp("Error contacting AI: " + err.message);
    }
    setAiLoading(false);
  };

  const suggestedQs = [
    "How can I match impedance to 50Ω?",
    "How do I shift resonant frequency to target?",
    "How can I increase antenna gain?",
    "What substrate thickness is optimal?",
  ];

  // SVG dimensions
  const margin = 8;
  const vbX = -p.subL / 2 - margin;
  const vbY = -p.subW / 2 - margin;
  const vbW = p.subL + 2 * margin;
  const vbH = p.subW + 2 * margin;
  const copperFill = "#c87533";
  const subFill = "#f0e0ce";

  const tabs = [
    { id: "design", label: "Design" },
    { id: "code", label: "Export VBA" },
    { id: "ai", label: "AI Advisor" },
  ];

  return (
    <div style={{ fontFamily: "'Inter', system-ui, sans-serif", background: "#0c1220", color: "#e2e8f0", minHeight: "100vh" }}>
      {/* Header */}
      <div style={{ maxWidth: 1100, margin: "0 auto", padding: "16px 16px 0" }}>
        <div style={{ display: "flex", alignItems: "baseline", gap: 12, flexWrap: "wrap", marginBottom: 8 }}>
          <h1 style={{ fontSize: 18, fontWeight: 700, color: "#22d3ee", margin: 0, letterSpacing: "-0.02em" }}>
            ◎ Ring Antenna Designer
          </h1>
          <span style={{ fontSize: 12, color: "#64748b" }}>Concentric double-ring microstrip · 2.45 GHz WiFi</span>
        </div>

        {/* Target freq + substrate preset */}
        <div style={{ display: "flex", gap: 16, alignItems: "center", marginBottom: 12, flexWrap: "wrap" }}>
          <label style={{ fontSize: 12, color: "#94a3b8", display: "flex", alignItems: "center", gap: 6 }}>
            Target
            <input type="number" value={p.targetF} step={0.01} min={0.5} max={10}
              onChange={e => set("targetF", parseFloat(e.target.value) || 2.45)}
              style={{ width: 72, background: "#1e293b", border: "1px solid #334155", borderRadius: 4, color: "#e2e8f0", padding: "3px 6px", fontFamily: "monospace", fontSize: 13 }} />
            GHz
          </label>
          <label style={{ fontSize: 12, color: "#94a3b8", display: "flex", alignItems: "center", gap: 6 }}>
            Substrate
            <select value="" onChange={e => { const pr = PRESETS[e.target.value]; if (pr) setP(prev => ({ ...prev, ...pr })); }}
              style={{ background: "#1e293b", border: "1px solid #334155", borderRadius: 4, color: "#94a3b8", padding: "3px 6px", fontSize: 12 }}>
              <option value="">presets...</option>
              {Object.keys(PRESETS).map(k => <option key={k} value={k}>{k}</option>)}
            </select>
          </label>
          <button onClick={() => setP(DEFAULTS)}
            style={{ fontSize: 11, color: "#94a3b8", background: "none", border: "1px solid #334155", borderRadius: 4, padding: "3px 10px", cursor: "pointer" }}>
            Reset
          </button>
        </div>

        {/* Tabs */}
        <div style={{ display: "flex", gap: 2, borderBottom: "1px solid #1e293b" }}>
          {tabs.map(t => (
            <button key={t.id} onClick={() => setTab(t.id)}
              style={{
                padding: "8px 16px", fontSize: 13, fontWeight: 500, cursor: "pointer", border: "none",
                background: tab === t.id ? "#1e293b" : "transparent",
                color: tab === t.id ? "#22d3ee" : "#64748b",
                borderRadius: "6px 6px 0 0",
                borderBottom: tab === t.id ? "2px solid #22d3ee" : "2px solid transparent",
              }}>
              {t.label}
            </button>
          ))}
        </div>
      </div>

      <div style={{ maxWidth: 1100, margin: "0 auto", padding: 16 }}>
        {/* =============== DESIGN TAB =============== */}
        {tab === "design" && (
          <div style={{ display: "flex", gap: 16, flexWrap: "wrap" }}>
            {/* Left: SVG + metrics */}
            <div style={{ flex: "1 1 400px", minWidth: 300 }}>
              {/* SVG */}
              <div style={{ background: "#0f172a", borderRadius: 8, border: "1px solid #1e293b", padding: 8, marginBottom: 12 }}>
                <svg viewBox={`${vbX} ${vbY} ${vbW} ${vbH}`} style={{ width: "100%", height: "auto", maxHeight: 360 }}>
                  {/* Grid */}
                  <defs>
                    <pattern id="grid" width="5" height="5" patternUnits="userSpaceOnUse">
                      <path d="M 5 0 L 0 0 0 5" fill="none" stroke="#1e293b" strokeWidth="0.15" />
                    </pattern>
                  </defs>
                  <rect x={vbX} y={vbY} width={vbW} height={vbH} fill="url(#grid)" />

                  {/* Substrate */}
                  <rect x={-p.subL / 2} y={-p.subW / 2} width={p.subL} height={p.subW}
                    fill={subFill} fillOpacity={0.12} stroke="#94a3b8" strokeWidth={0.3} strokeDasharray="1.5,1" />

                  {/* Outer Ring */}
                  <path d={ringPath(p.ctrX, 0, p.orOuter, p.orInner)}
                    fill={copperFill} fillRule="evenodd" fillOpacity={0.85} />

                  {/* Inner Ring */}
                  <path d={ringPath(p.ctrX, 0, p.irOuter, p.irInner)}
                    fill={copperFill} fillRule="evenodd" fillOpacity={0.85} />

                  {/* Connector bridge */}
                  <rect x={Math.min(connX1, connX2)} y={-p.connW / 2}
                    width={Math.abs(connX1 - connX2)} height={p.connW}
                    fill={copperFill} fillOpacity={0.85} />

                  {/* Feed strip */}
                  <rect x={feedStartX} y={-p.feedW / 2}
                    width={Math.max(feedEndX - feedStartX, 0)} height={p.feedW}
                    fill={copperFill} fillOpacity={0.85} />

                  {/* Port indicator */}
                  <line x1={feedEndX} y1={-p.feedW / 2 - 1} x2={feedEndX} y2={p.feedW / 2 + 1}
                    stroke="#ef4444" strokeWidth={0.6} />
                  <text x={feedEndX + 1} y={p.feedW / 2 + 3} fill="#ef4444" fontSize={2.5}
                    style={{ fontFamily: "monospace" }}>Port 1</text>

                  {/* Center mark */}
                  <line x1={p.ctrX - 1} y1={0} x2={p.ctrX + 1} y2={0} stroke="#64748b" strokeWidth={0.15} />
                  <line x1={p.ctrX} y1={-1} x2={p.ctrX} y2={1} stroke="#64748b" strokeWidth={0.15} />

                  {/* Dimension: outer ring diameter */}
                  <line x1={p.ctrX - p.orOuter} y1={p.subW / 2 - 2} x2={p.ctrX + p.orOuter} y2={p.subW / 2 - 2}
                    stroke="#22d3ee" strokeWidth={0.2} markerEnd="none" />
                  <line x1={p.ctrX - p.orOuter} y1={p.subW / 2 - 3} x2={p.ctrX - p.orOuter} y2={p.subW / 2 - 1}
                    stroke="#22d3ee" strokeWidth={0.15} />
                  <line x1={p.ctrX + p.orOuter} y1={p.subW / 2 - 3} x2={p.ctrX + p.orOuter} y2={p.subW / 2 - 1}
                    stroke="#22d3ee" strokeWidth={0.15} />
                  <text x={p.ctrX} y={p.subW / 2 - 3} fill="#22d3ee" fontSize={2.2} textAnchor="middle"
                    style={{ fontFamily: "monospace" }}>⌀{(p.orOuter * 2).toFixed(1)}</text>

                  {/* Dimension: substrate length */}
                  <text x={0} y={-p.subW / 2 - 2} fill="#64748b" fontSize={2} textAnchor="middle"
                    style={{ fontFamily: "monospace" }}>{p.subL}×{p.subW} mm</text>

                  {/* Scale bar */}
                  <line x1={p.subL / 2 - 10} y1={p.subW / 2 + 4} x2={p.subL / 2} y2={p.subW / 2 + 4}
                    stroke="#64748b" strokeWidth={0.3} />
                  <text x={p.subL / 2 - 5} y={p.subW / 2 + 6.5} fill="#64748b" fontSize={1.8} textAnchor="middle"
                    style={{ fontFamily: "monospace" }}>10 mm</text>
                </svg>
              </div>

              {/* Warnings */}
              {warnings.length > 0 && (
                <div style={{ background: "#7f1d1d22", border: "1px solid #991b1b", borderRadius: 6, padding: "8px 12px", marginBottom: 12, fontSize: 12, color: "#fca5a5" }}>
                  {warnings.map((w, i) => <div key={i}>⚠ {w}</div>)}
                </div>
              )}

              {/* Performance metrics */}
              <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(130px, 1fr))", gap: 8 }}>
                <MetricCard label="Resonant freq" value={calc.fRes.toFixed(3)} unit="GHz"
                  warn={Math.abs(calc.delta) > 0.1} />
                <MetricCard label="Δ from target" value={(calc.delta > 0 ? "+" : "") + (calc.delta * 1000).toFixed(0)} unit="MHz"
                  warn={Math.abs(calc.delta) > 0.1} />
                <MetricCard label="Feed Z₀" value={calc.z0.toFixed(1)} unit="Ω"
                  warn={Math.abs(calc.z0 - 50) > 30} />
                <MetricCard label="ε_eff" value={calc.ee.toFixed(3)} unit="" />
                <MetricCard label="λ₀" value={calc.lam0.toFixed(1)} unit="mm" />
                <MetricCard label="λ_guided" value={calc.lamG.toFixed(1)} unit="mm" />
                <MetricCard label="h / λ₀" value={(calc.hLam * 100).toFixed(2)} unit="%" />
                <MetricCard label="Ring width" value={calc.rw.toFixed(1)} unit="mm"
                  warn={calc.rw <= 0} />
              </div>

              <div style={{ fontSize: 11, color: "#475569", marginTop: 8, lineHeight: 1.5 }}>
                Analytical estimates use the mean-circumference model for the outer ring's TM₁₁ mode.
                Actual performance depends on coupling effects, connector geometry, and fringing fields — verify with CST simulation.
              </div>
            </div>

            {/* Right: Controls */}
            <div style={{ flex: "0 0 320px", minWidth: 280 }}>
              <Section title="Substrate">
                <Slider label="Length" value={p.subL} min={20} max={100} step={1} unit="mm" onChange={v => set("subL", v)} />
                <Slider label="Width" value={p.subW} min={15} max={80} step={1} unit="mm" onChange={v => set("subW", v)} />
                <Slider label="Height" value={p.subH} min={0.2} max={3.2} step={0.1} unit="mm" onChange={v => set("subH", v)} />
                <Slider label="εr" value={p.epsR} min={1.5} max={12} step={0.01} unit="" onChange={v => set("epsR", v)} />
                <Slider label="tan δ" value={p.tanD} min={0} max={0.05} step={0.0001} unit="" onChange={v => set("tanD", v)} />
              </Section>

              <Section title="Outer Ring">
                <Slider label="Outer R" value={p.orOuter} min={3} max={30} step={0.5} unit="mm" onChange={v => set("orOuter", v)} />
                <Slider label="Inner R" value={p.orInner} min={2} max={25} step={0.5} unit="mm" onChange={v => set("orInner", v)} />
              </Section>

              <Section title="Inner Ring">
                <Slider label="Outer R" value={p.irOuter} min={1} max={20} step={0.5} unit="mm" onChange={v => set("irOuter", v)} />
                <Slider label="Inner R" value={p.irInner} min={0.5} max={15} step={0.5} unit="mm" onChange={v => set("irInner", v)} />
              </Section>

              <Section title="Position & Feed">
                <Slider label="Center X" value={p.ctrX} min={-20} max={20} step={0.5} unit="mm" onChange={v => set("ctrX", v)} />
                <Slider label="Feed W" value={p.feedW} min={0.3} max={6} step={0.1} unit="mm" onChange={v => set("feedW", v)} />
                <Slider label="Bridge W" value={p.connW} min={0.3} max={6} step={0.1} unit="mm" onChange={v => set("connW", v)} />
              </Section>

              <Section title="Quick Actions">
                <button onClick={() => {
                  const targetMeanR = C / (2 * Math.PI * p.targetF * 1e9 * Math.sqrt(calc.ee)) * 1e3;
                  const ringW = p.orOuter - p.orInner;
                  const newInner = targetMeanR - ringW / 2;
                  const newOuter = targetMeanR + ringW / 2;
                  if (newInner > 0) setP(prev => ({ ...prev, orOuter: Math.round(newOuter * 2) / 2, orInner: Math.round(newInner * 2) / 2 }));
                }} style={{
                  width: "100%", padding: "8px 0", background: "#164e63", border: "1px solid #22d3ee",
                  borderRadius: 6, color: "#22d3ee", fontSize: 13, cursor: "pointer", fontWeight: 500, marginBottom: 6,
                }}>
                  ⟳ Auto-tune outer ring to {p.targetF} GHz
                </button>
                <button onClick={() => {
                  const target50W = p.subH * 1.0; // rough W/h≈2 for 50Ω on this εr
                  // More precise: solve Z0 formula for W given Z0=50
                  // For W/h>1: W/h = (120π/(Z0*sqrt(ee))) - 1.393 - ...  (iterative)
                  // Simplified: for RO4350B at 0.5mm, 50Ω ≈ 1.1mm wide
                  const ee_est = epsEff(p.epsR, target50W, p.subH);
                  let wGuess = p.feedW;
                  for (let i = 0; i < 20; i++) {
                    const z = feedZ0(p.epsR, wGuess, p.subH);
                    wGuess *= z / 50; // Newton-like scaling
                    if (wGuess < 0.1) wGuess = 0.1;
                    if (wGuess > 10) wGuess = 10;
                  }
                  set("feedW", Math.round(wGuess * 10) / 10);
                }} style={{
                  width: "100%", padding: "8px 0", background: "#1e293b", border: "1px solid #334155",
                  borderRadius: 6, color: "#94a3b8", fontSize: 13, cursor: "pointer",
                }}>
                  Match feed to 50 Ω
                </button>
              </Section>
            </div>
          </div>
        )}

        {/* =============== CODE TAB =============== */}
        {tab === "code" && (
          <div>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 8 }}>
              <span style={{ fontSize: 13, color: "#94a3b8" }}>
                CST Macro with current parameters — paste into CST's VBA editor
              </span>
              <button onClick={() => {
                if (codeRef.current) {
                  codeRef.current.select();
                  document.execCommand("copy");
                }
              }} style={{
                padding: "6px 14px", background: "#164e63", border: "1px solid #22d3ee",
                borderRadius: 4, color: "#22d3ee", fontSize: 12, cursor: "pointer",
              }}>
                Copy code
              </button>
            </div>
            <div style={{ position: "relative" }}>
              <textarea ref={codeRef} readOnly value={vba}
                style={{
                  width: "100%", height: 500, background: "#0f172a", border: "1px solid #1e293b",
                  borderRadius: 8, color: "#a5f3fc", fontFamily: "monospace", fontSize: 12,
                  padding: 16, resize: "vertical", lineHeight: 1.6,
                }} />
            </div>
          </div>
        )}

        {/* =============== AI TAB =============== */}
        {tab === "ai" && (
          <div style={{ maxWidth: 700 }}>
            <div style={{ fontSize: 13, color: "#94a3b8", marginBottom: 12, lineHeight: 1.6 }}>
              Ask the AI advisor about your antenna design. It sees all your current parameters and estimated performance.
            </div>

            {/* Suggested questions */}
            <div style={{ display: "flex", flexWrap: "wrap", gap: 6, marginBottom: 12 }}>
              {suggestedQs.map((q, i) => (
                <button key={i} onClick={() => { setAiQuery(q); askAI(q); }}
                  style={{
                    padding: "5px 12px", background: "#1e293b", border: "1px solid #334155",
                    borderRadius: 20, color: "#94a3b8", fontSize: 12, cursor: "pointer",
                    transition: "border-color 0.15s",
                  }}
                  onMouseEnter={e => e.target.style.borderColor = "#22d3ee"}
                  onMouseLeave={e => e.target.style.borderColor = "#334155"}>
                  {q}
                </button>
              ))}
            </div>

            {/* Input */}
            <div style={{ display: "flex", gap: 8, marginBottom: 16 }}>
              <input type="text" value={aiQuery}
                onChange={e => setAiQuery(e.target.value)}
                onKeyDown={e => e.key === "Enter" && askAI()}
                placeholder="Ask about your antenna design..."
                style={{
                  flex: 1, background: "#1e293b", border: "1px solid #334155", borderRadius: 6,
                  color: "#e2e8f0", padding: "8px 12px", fontSize: 13,
                }} />
              <button onClick={() => askAI()} disabled={aiLoading}
                style={{
                  padding: "8px 20px", background: aiLoading ? "#1e293b" : "#164e63",
                  border: `1px solid ${aiLoading ? "#334155" : "#22d3ee"}`,
                  borderRadius: 6, color: aiLoading ? "#64748b" : "#22d3ee",
                  fontSize: 13, cursor: aiLoading ? "wait" : "pointer", fontWeight: 500,
                }}>
                {aiLoading ? "Thinking..." : "Ask"}
              </button>
            </div>

            {/* Response */}
            {(aiResp || aiLoading) && (
              <div style={{
                background: "#1e293b", border: "1px solid #334155", borderRadius: 8,
                padding: 16, fontSize: 13, lineHeight: 1.7, color: "#cbd5e1",
                whiteSpace: "pre-wrap",
              }}>
                {aiLoading ? (
                  <span style={{ color: "#64748b" }}>Analyzing your design parameters...</span>
                ) : aiResp}
              </div>
            )}

            <div style={{ fontSize: 11, color: "#475569", marginTop: 12, lineHeight: 1.5 }}>
              Powered by Claude (Anthropic API). The advisor receives your current parameter values
              and analytical estimates to provide context-aware engineering guidance.
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
